
services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./html:/usr/share/nginx/html
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: system
      POSTGRES_PASSWORD: systempasswd
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
